### ISSUE TITLE
Testnet contract links

### ISSUE THREAD

**Issue by developerdavi** [kuyawa/littlejohn#1]
Hi!

Just noticed that the links provided to the contracts are redirecting to the testnet block explorer.

Like BRL/BNB: https://testnet.bscscan.com/address/0xA9AB46C8eE740b4A833e0FDC2d3875c5065F25fd

And all the others. Is it running on BSC mainnet?

Also, is MetaMask supported at all running on ETH mainnet?

By the way, congrats for the nice project :)

**Comment by kuyawa** [comment]
Hi Davi, LittleJohn is running on Testnet for the hackathon as it is expensive to update the prices of all currencies every hour and contract creation is also expensive. Both Metamask and Binance Wallet can run on Testnet with no issues.

Thank you for feedback and support

**Comment by developerdavi** [comment]
Got it! Nice project btw
